// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/adapters/cart_gateway.go

// Package mock_adapters is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	gomock "github.com/golang/mock/gomock"
	
	adapters "food-app/domain/adapters"
)

// MockICartGateway is a mock of ICartGateway interface.
type MockICartGateway struct {
	ctrl     *gomock.Controller
	recorder *MockICartGatewayMockRecorder
}

// MockICartGatewayMockRecorder is the mock recorder for MockICartGateway.
type MockICartGatewayMockRecorder struct {
	mock *MockICartGateway
}

// NewMockICartGateway creates a new mock instance.
func NewMockICartGateway(ctrl *gomock.Controller) *MockICartGateway {
	mock := &MockICartGateway{ctrl: ctrl}
	mock.recorder = &MockICartGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICartGateway) EXPECT() *MockICartGatewayMockRecorder {
	return m.recorder
}

// GetFilledCart mocks base method.
func (m *MockICartGateway) GetFilledCart() adapters.ICart {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilledCart")
	ret0, _ := ret[0].(adapters.ICart)
	return ret0
}

// GetFilledCart indicates an expected call of GetFilledCart.
func (mr *MockICartGatewayMockRecorder) GetFilledCart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilledCart", reflect.TypeOf((*MockICartGateway)(nil).GetFilledCart))
}
