version: '3.8'
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
    driver: local
